### ISSUE TITLE
Gutenberg Editor does not show the block

### ISSUE THREAD

**Issue by taalz** [herewithme/simple-taxonomy#11]
Anyone found a solution to the Gutenberg editor? The post does not show the block to enter the value for the custom taxonomy.

**Comment by maxlegault** [comment]
I just ran into that issue and found a workaround. As stated in Wordpress' doc in here https://developer.wordpress.org/reference/functions/register_taxonomy/ the `show_in_rest` boolean must be passed in order for a taxonomy to show up in the block editor.

By looking at the `prepareArgs()` method in the `inc/class.client.php` file, the values seems to be missing. So my fix was to edit that file and add the value. It's not a complete fix since there should be a configuration in the UI to specify it per taxonomy, but it works for me since I always want them to show up in the block editor.

```php
	public static function prepareArgs( $taxonomy ) {
		// ...

		return array(
			'hierarchical' => $taxonomy['hierarchical'],
			'update_count_callback' => '_update_post_term_count', // use default WP callback
			'rewrite' => $taxonomy['rewrite'],
			'query_var' => $taxonomy['query_var'],
			'public' => (boolean) $taxonomy['public'],
			'show_ui' => (boolean) $taxonomy['show_ui'],
			'show_tagcloud' => (boolean) $taxonomy['show_tagcloud'],
			'labels' => $taxonomy['labels'],
			'capabilities' => $taxonomy['capabilities'],
			'show_in_nav_menus' => (boolean) $taxonomy['show_in_nav_menus'],
                         // This is the line to add
			'show_in_rest' => true
		);
	}
```
